spring.application.name=ProductsMicroservice
server.port=0
#Random port number generate by spring boot
spring.kafka.producer.bootstrap-servers=localhost:9092, localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
#spring.kafka.producer.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=1000

# - linger.ms=0: Envia as mensagens imediatamente, priorizando baixa latência (sem aguardar para agrupar em lote).
# - request.timeout.ms=30000: Tempo limite de 30 segundos para o broker responder a cada requisição individual.
# - delivery.timeout.ms=120000: Limite máximo de 2 minutos para o ciclo completo de entrega de uma mensagem,
#   incluindo o tempo de espera no buffer, tentativas de reenvio (retries) e respostas do broker.
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000
